### ISSUE TITLE
CR+LF vs. LF should be selectable

### ISSUE THREAD

**Issue by sjm42** [agerasev/tokio-lxi#4]
I was trying to control my Siglent SPD3303X lab power supply, and found out that it hates the carriage return.

[https://siglentna.com/operating-tip/spd-programming-tips/](https://siglentna.com/operating-tip/spd-programming-tips/)

The problem is, send() is transmitting this:

        `self.stream.write_all(b"\r\n").await?;`

Ideally, we should be able to select the line end from CR, LF or CR+LF. Don't know if there are weird devices that would need LF+CR even.

**Comment by agerasev** [comment]
The feature was added in #5, thank you for your contribution! I'm closing the issue.
